version: 2.1

aliases:
  - &docker_image
    - image: cimg/node:24.19.0

  - &current_workspace
    attach_workspace: { at: '.' }

jobs:
  install-dependencies:
    docker: *docker_image
    steps:
      - checkout
      - run: node --version
      - run: npm ci
      - persist_to_workspace:
          root: '.'
          paths:
            - 'node_modules/*'

  check-typescript:
    docker: *docker_image
    steps:
      - checkout
      - *current_workspace
      - run: npm run type:check

  check-format:
    docker: *docker_image
    steps:
      - checkout
      - *current_workspace
      - run: npm run format

  check-lint:
    docker: *docker_image
    steps:
      - checkout
      - *current_workspace
      - run: npm run lint

  check-build:
    docker: *docker_image
    steps:
      - checkout
      - *current_workspace
      - run: npm run build

workflows:
  validations:
    jobs:
      - install-dependencies
      - check-typescript:
          requires:
            - install-dependencies
      - check-format:
          requires:
            - install-dependencies
      - check-lint:
          requires:
            - install-dependencies
      - check-build:
          requires:
            - install-dependencies
